#!/bin/sh

# SPDX-FileCopyrightText: © 2022 Peter Lemenkov
#
# SPDX-License-Identifier: CC0-1.0

. "`dirname "$0"`/../functions"

DIR=$1

autotrace -report-progress -centerline -input-format BMP $DIR/three_lines.bmp -output-format svg -output-file $DIR/three_lines.svg
RESULT=$?

if [ $RESULT -eq 0 ] && [ -s $DIR/three_lines.svg ] ; then
    rm -f $DIR/three_lines.svg
    ok
else
    fail
fi
