#!/bin/sh

. "`dirname "$0"`/../functions"

DIR=$1

autotrace -output-file $DIR/trace01.idraw -output-format idraw -report-progress -input-format BMP $DIR/trace01.bmp
RESULT=$?
rm -f $DIR/trace01.idraw

if [ $RESULT -ne 0 ]; then
    fail
fi
ok
