#!/bin/sh

# SPDX-FileCopyrightText: © 2022-2025 Peter Lemenkov
#
# SPDX-License-Identifier: CC0-1.0

. "`dirname "$0"`/../functions"

DIR=$1

autotrace -output-file $DIR/trace01.pdf -output-format pdf -report-progress -input-format BMP $DIR/trace01.bmp
RESULT=$?
rm -f $DIR/trace01.pdf

if [ $RESULT -ne 0 ]; then
    fail
fi
ok
