#!/bin/sh

. "`dirname "$0"`/../functions"

DIR=$1

autotrace -report-progress -centerline -input-format XPM $DIR/lego_5.xpm -output-format svg -output-file $DIR/lego_5.svg
RESULT=$?

if [ $RESULT -eq 0 ] && [ -s $DIR/lego_5.svg ] ; then
    rm -f $DIR/lego_5.svg
    ok
else
    fail
fi
