#!/bin/sh

# SPDX-FileCopyrightText: © 2022-2023 Peter Lemenkov
# SPDX-FileCopyrightText: © 2023 Jaroslav Škarvada
#
# SPDX-License-Identifier: CC0-1.0

. "`dirname "$0"`/../functions"

DIR=$1

# Check whether ImageMagick support is enabled and hence we support XPM
autotrace -list-input-formats 2>&1 | grep -q xpm
RESULT=$?

if [ $RESULT -ne 0 ] ; then
    XPM=0
else
    XPM=1
fi

autotrace -report-progress -centerline -input-format XPM $DIR/lego_5.xpm -output-format svg -output-file $DIR/lego_5.svg
RESULT=$?

if [ $RESULT -eq 0 ] && [ -s $DIR/lego_5.svg ] ; then
    rm -f $DIR/lego_5.svg
    ok
else
    if [ $XPM -eq 0 ] ; then
        expected_fail
    else
        fail
    fi
fi
